name: flymedia_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fluentui_icons: ^1.0.0 
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  file_selector_macos: ^0.9.3+3
  flutter_screenutil: ^5.9.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  google_fonts: ^4.0.3
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  loading_overlay: ^0.3.0
  provider: ^6.1.1
  pinput: ^3.0.1
  unicons: ^2.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/