name: flymedia_admin
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  file_selector_macos: ^0.9.3+3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  fluentui_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  google_fonts: ^4.0.3
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  loading_overlay: ^0.3.0
  pinput: ^3.0.1
  provider: ^6.1.1
  shared_preferences: ^2.1.0
  unicons: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
